#!/bin/bash

# I'm using this command to build the site, and push it to a remote server using 
# rsync over SSH. You ideally need your ~/.ssh/config set up with the host's name
# and your private/public key pair set up.
# 
# I always un this command from the local jekyll directory, so the relative
# directory: _site/ will send the right thing to the remote server.

src="_site/"
# compufix is my .ssh/config entry for my own server
dst="compufix:/var/www/test.hobartmakers/"

bundle exec jekyll build 
rsync -rvl --delete --stats --progress "$src" "$dst"
# recursive, verbose, copy symlinks as symlinks, show transfer stats, show progress

